markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Katie Ball
production_url : http://roachhaus.github.io/up
description: "Througths, ramblings, technology, tutorials, codes, projects and other things by Katie Ball."
disqus_shortname: caarlos0blog
analytics: UA-GOOGLE-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Katie Ball
  github : roachhd
  twitter : meatball
  email: hi@roachhd.com
